### ISSUE TITLE
Day 4 - Arrows

### ISSUE THREAD

**Issue by vineetkumardoshi** [giannioudis/7-Days-of-JavaScript#2]
The problem has been edited and the solution looks something like this.

```
var my_function = (some_array) => some_array.map( (item) => item % 2 === 0? ++item: --item);
```

THANKS

**Comment by giannioudis** [comment]
has this been tested and received a  pass? why complicate the answer just want to know your input!

**Comment by omgphil** [comment]
Just read the problem, I will make the modification, thanks for the head up!
