### ISSUE TITLE
Day 3: Find the Second Largest Number in an Array

### ISSUE THREAD

**Issue by brosahay** [giannioudis/7-Days-of-JavaScript#3]
`8
8
6
1
2`
Doesn't work against this input test case .

**Comment by omgphil** [comment]
actually it does I just tested it.

```
 var maxi = Math.max.apply(null, myArray);
console.log(Math.max.apply(null, myArray.filter((x) => x != maxi)));  
```

the conditions here find the second largest number as per the question. Please let me know if you need me to go into further.
